AllCops:
  TargetRubyVersion: 3.1.2
  Exclude:
      - 'bin/bundle'
      - 'db/schema.rb'
      - 'coverage/**/*'
Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Layout/LineLength:
  Max: 120

require:
  - rubocop-rails
  - rubocop-performance
  # - rubocop-rspec
