AllCops:
  TargetRubyVersion: 3.1.2
  Exclude:
      - 'bin/bundle'
      - 'db/schema.rb'
      - 'coverage/**/*'
Style/Documentation:
  Enabled: false
  Exclude:
      - 'tmp/**/*'
Style/AsciiComments:
  Enabled: false